version: '3'

services:
  backend:
    container_name: talep_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8460:8460"
    environment:
      - NODE_ENV=production
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=arac_rezervasyonn
      - PORT=8460
      - CORS_ORIGIN=https://talep.onder.org.tr
    volumes:
      - backend_data:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - talep-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8460/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  frontend:
    container_name: talep_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://talep.onder.org.tr
    volumes:
      - frontend_data:/app/dist
    depends_on:
      - backend
    networks:
      - talep-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  db:
    container_name: mysqldb
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: arac_rezervasyonn
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - talep-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      interval: 20s
      timeout: 5m
      retries: 10
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  phpmyadmin:
    container_name: talep_phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
    depends_on:
      - db
    networks:
      - talep-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    container_name: talep_nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./logs:/var/log/nginx
      - frontend_data:/usr/share/nginx/html
    depends_on:
      - frontend
      - backend
      - phpmyadmin
    networks:
      - talep-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  talep-network:
    name: talep-network
    driver: bridge

volumes:
  backend_data:
  frontend_data:
  db_data: