version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: talep-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=https://talep.onder.org.tr/api
    networks:
      - talep-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: talep-backend
    restart: unless-stopped
    ports:
      - "8060:8060"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=arac_rezervasyonn
      - PORT=8060
    depends_on:
      - mysql
    networks:
      - talep-network

  mysql:
    image: mysql:8.0
    container_name: talep-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=arac_rezervasyonn
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - talep-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: talep-phpmyadmin
    restart: unless-stopped
    ports:
      - "5083:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - talep-network

networks:
  talep-network:
    driver: bridge

volumes:
  mysql_data: